"""Initial migration

Revision ID: 3d14e75c8030
Revises: 
Create Date: 2026-04-17 10:25:53.837672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d14e75c8030'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('schedule_template_path', sa.String(), nullable=True),
    sa.Column('evolution_api_url', sa.String(), nullable=True),
    sa.Column('evolution_api_key', sa.String(), nullable=True),
    sa.Column('evolution_instance_name', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_churches_id'), 'churches', ['id'], unique=False)
    op.create_index(op.f('ix_churches_slug'), 'churches', ['slug'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('ATIVO', 'EXCLUIDO', 'VISITANTE', 'TRANSFERIDO', 'AFASTADO', name='memberstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('data_batismo', sa.DateTime(), nullable=True),
    sa.Column('consecutive_refusals', sa.Integer(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_member_church_status', 'members', ['church_id', 'status'], unique=False)
    op.create_index(op.f('ix_members_church_id'), 'members', ['church_id'], unique=False)
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_phone', sa.String(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_church_id'), 'notification_logs', ['church_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('CARGO', 'FUNCAO', name='positiontype'), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_church_id'), 'positions', ['church_id'], unique=False)
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_templates_church_id'), 'service_templates', ['church_id'], unique=False)
    op.create_index(op.f('ix_service_templates_id'), 'service_templates', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_master', sa.Boolean(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_church_email', 'users', ['church_id', 'email'], unique=False)
    op.create_index(op.f('ix_users_church_id'), 'users', ['church_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_church_id'), 'documents', ['church_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('member_absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_absences_church_id'), 'member_absences', ['church_id'], unique=False)
    op.create_index(op.f('ix_member_absences_id'), 'member_absences', ['id'], unique=False)
    op.create_table('member_positions',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('member_id', 'position_id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('card_path', sa.String(), nullable=True),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_church_date', 'schedules', ['church_id', 'event_date'], unique=False)
    op.create_index(op.f('ix_schedules_church_id'), 'schedules', ['church_id'], unique=False)
    op.create_index(op.f('ix_schedules_id'), 'schedules', ['id'], unique=False)
    op.create_table('template_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_positions_id'), 'template_positions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_positions_id'), table_name='template_positions')
    op.drop_table('template_positions')
    op.drop_index(op.f('ix_schedules_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_church_id'), table_name='schedules')
    op.drop_index('idx_schedule_church_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_table('member_positions')
    op.drop_index(op.f('ix_member_absences_id'), table_name='member_absences')
    op.drop_index(op.f('ix_member_absences_church_id'), table_name='member_absences')
    op.drop_table('member_absences')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_church_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_church_id'), table_name='users')
    op.drop_index('idx_user_church_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_templates_id'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_church_id'), table_name='service_templates')
    op.drop_table('service_templates')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_church_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_church_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_index(op.f('ix_members_church_id'), table_name='members')
    op.drop_index('idx_member_church_status', table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_churches_slug'), table_name='churches')
    op.drop_index(op.f('ix_churches_id'), table_name='churches')
    op.drop_table('churches')
    # ### end Alembic commands ###
